routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['install']], function () {
	
	//Webiste Routes
	Route::get('/shop', 'Website\WebsiteController@shop');
	Route::get('/product/{slug}', 'Website\WebsiteController@product');
	Route::get('/categories/{slug}', 'Website\WebsiteController@categories');
	Route::get('/brands/{slug?}', 'Website\WebsiteController@brands');
	Route::get('/tags/{slug}', 'Website\WebsiteController@tags');
	Route::get('/cart', 'Website\WebsiteController@cart');
	Route::get('/checkout', 'Website\WebsiteController@checkout');
	Route::post('/send_message', 'Website\WebsiteController@send_message');
	Route::post('/subscribe_newsletter', 'Website\WebsiteController@subscribe_newsletter');
	Route::match(['get','post'],'/sign_in', 'Website\CustomerController@sign_in');
	Route::match(['get','post'],'/sign_up', 'Website\CustomerController@sign_up');
	Route::get('/sign_out', 'Website\CustomerController@sign_out');


	//Need to login for View this page
	Route::group(['middleware' => ['verified']], function () {
		Route::get('/wish_list/{product_id?}', 'Website\WebsiteController@wish_list');
		Route::get('/remove_wishlist/{product_id?}', 'Website\WebsiteController@remove_wishlist');
		Route::get('/my_account/{page?}', 'Website\CustomerController@my_account');
		Route::get('/download_product/{product_id}', 'Website\CustomerController@download_product');
		Route::get('/order_details/{order_id}', 'Website\CustomerController@order_details');
		Route::post('/update_account', 'Website\CustomerController@update_account');
		Route::post('/update_password', 'Website\CustomerController@update_password');
		Route::match(['get','post'], '/add_new_address', 'Website\CustomerController@add_new_address');
		Route::match(['get','patch'], '/update_address/{address_id}', 'Website\CustomerController@update_address');
		Route::get('/delete_address/{address_id}', 'Website\CustomerController@delete_address');
		Route::post('comments/store', 'Website\CommentController@store')->name('comments.store');
		Route::post('reviews/store', 'Website\ReviewsController@store')->name('reviews.store');
	});


	//Apply Tax
	Route::get('/apply_tax/{shipping_state?}/{billing_state?}', 'Website\CheckoutController@apply_tax');
	Route::post('/make_order', 'Website\CheckoutController@make_order');
	Route::get('/payment/{order_id}', 'Website\CheckoutController@payment');

	//Get Variation Price
	Route::post('products/get_variation_price/{product_id}','ProductController@get_variation_price');

	//Add to Cart
	Route::post('/add_to_cart/{product_id}', 'Website\CartController@add_to_cart');
	Route::post('/update_cart', 'Website\CartController@update_cart');
	Route::post('/apply_coupon', 'Website\CartController@apply_coupon');
	Route::get('/remove_coupon/{name}', 'Website\CartController@remove_coupon');
	Route::get('/remove_cart_item/{id}', 'Website\CartController@remove_cart_item');
	Route::get('/shipping_method/{name}', 'Website\CartController@shipping_method');

	//Payment Gateways
	Route::get('gateway/paypal_payment_authorize/{paypal_order_id}/{order_id}', 'Website\GatewayController@paypal_payment_authorize');
	Route::post('gateway/stripe_payment_authorize/{order_id}', 'Website\GatewayController@stripe_payment_authorize');
	Route::post('gateway/razorpay_payment_authorize/{order_id}', 'Website\GatewayController@razorpay_payment_authorize');
	Route::get('gateway/paystack_payment_authorize/{order_id}/{reference}', 'Website\GatewayController@paystack_payment_authorize');
	Route::get('gateway/confirm_order/{type}/{order_id}', 'Website\GatewayController@confirm_order'); //This route is for manual payment

	
	Route::group(['prefix'=> 'admin'], function () {
//	    Route::get('/', function(){
//	    	return redirect('admin/login');
//	    });
	    Auth::routes(['verify' => true]);
	});
  
	Route::get('/logout', 'Auth\LoginController@logout');
	Route::get('/{slug?}', 'Website\WebsiteController@index');
	
	Route::group(['middleware' => ['auth','verified'], 'prefix'=> 'admin'], function () {


	    //Contact
        Route::get('/contact_us', 'ContactUsController@index')->name('contact_us');

        //Slide

        Route::get('/slide', 'SlideController@index')->name('slide.index');
        Route::get('/slide/create', 'SlideController@create')->name('slide.create');
        Route::post('/slide/store','SlideController@store')->name('slide.store');
        Route::get('/slide/edit/{id}','SlideController@edit')->name('slide.edit');
        Route::post('/slide/update','SlideController@update')->name('slide.update');
        Route::delete('/slide/destroy/{id}','SlideController@destroy')->name('slide.destroy');

        //Product

        Route::get('products/search','ProductController@search')->name('products.search');
		Route::get('dashboard', 'DashboardController@index')->middleware('groupPermission:admin,user,customer');
		
		//Profile Controller
		Route::get('profile/edit', 'ProfileController@edit')->middleware('groupPermission:admin,user');
		Route::post('profile/update', 'ProfileController@update')->middleware('groupPermission:admin,user');
		Route::get('profile/change_password', 'ProfileController@change_password')->middleware('groupPermission:admin,user');
		Route::post('profile/update_password', 'ProfileController@update_password')->middleware('groupPermission:admin,user');
		

		/** Admin Only Route **/
		Route::group(['middleware' => ['admin']], function () {


			//User Management
			Route::resource('users','UserController');

			//User Roles
			Route::resource('roles','RoleController');
			
			//Permission Controller
		    Route::get('permission/control/{user_id?}', 'PermissionController@index')->name('permission.index');
			Route::post('permission/store', 'PermissionController@store')->name('permission.store');

			
			//Language Controller
			Route::resource('languages','LanguageController');	
			
			//Utility Controller
			Route::match(['get', 'post'],'general_settings/{store?}', 'UtilityController@settings')->name('settings.update_settings');
			Route::match(['get', 'post'],'theme_option/{page?}/{store?}', 'UtilityController@theme_option')->name('theme_option.update');
			Route::post('upload_logo', 'UtilityController@upload_logo')->name('settings.uplaod_logo');
			Route::get('database_backup_list', 'UtilityController@database_backup_list')->name('database_backups.list');
			Route::get('create_database_backup', 'UtilityController@create_database_backup')->name('database_backups.create');
			Route::delete('destroy_database_backup/{id}', 'UtilityController@destroy_database_backup');
			Route::get('download_database_backup/{id}', 'UtilityController@download_database_backup')->name('database_backups.download');
			Route::post('remove_cache', 'UtilityController@remove_cache')->name('settings.remove_cache');

			//Email Template
			Route::resource('email_templates','EmailTemplateController')->only([
				'index', 'show', 'edit', 'update'
			]);

			//Shipping Methods
			Route::get('shipping_methods', 'UtilityController@shipping_methods')->name('settings.shipping_methods');
			
			
		});

        /** Dynamic Permission **/
		Route::group(['middleware' => ['permission']], function () {

			Route::get('dashboard/total_sales_widget', 'DashboardController@total_sales_widget')->name('dashboard.total_sales_widget');
			Route::get('dashboard/current_day_sales_widget', 'DashboardController@current_day_sales_widget')->name('dashboard.current_day_sales_widget');
			Route::get('dashboard/pending_order_widget', 'DashboardController@pending_order_widget')->name('dashboard.pending_order_widget');
			Route::get('dashboard/total_product_widget', 'DashboardController@total_product_widget')->name('dashboard.total_product_widget');
			Route::get('dashboard/weekly_sales_widget', 'DashboardController@weekly_sales_widget')->name('dashboard.weekly_sales_widget');
			Route::get('dashboard/top_view_items_widget', 'DashboardController@top_view_items_widget')->name('dashboard.top_view_items_widget');
			Route::get('dashboard/recent_order_widget', 'DashboardController@recent_order_widget')->name('dashboard.recent_order_widget');
			
			//Media Controller
			Route::get('media/get_table_data/{type?}/{select_type?}','MediaController@get_table_data');
			Route::resource('media','MediaController')->except([
				'edit', 'update'
			]);

			//Order Controller
			Route::get('orders/get_table_data','OrderController@get_table_data');
			Route::resource('orders','OrderController')->except([
			    'create', 'store', 'edit'
			]);

			//Transaction Controller
			Route::get('transactions/get_table_data','TransactionController@get_table_data');
			Route::get('transactions','TransactionController@index')->name('transactions.index');

			//Product Controller
			Route::post('products/generate_variations','ProductController@generate_variations');
			Route::get('products/get_table_data','ProductController@get_table_data');

			Route::resource('products','ProductController');

			//Comments Controller
			Route::get('product_comments/get_table_data','CommentController@get_table_data');
			Route::get('product_comments/destroy/{id}','CommentController@destroy')->name('product_comments.destroy');
			Route::resource('product_comments','CommentController')->only([
			    'index', 'show'
			]);

			//Reviews Controller
			Route::get('product_reviews/get_table_data','ReviewsController@get_table_data');
			Route::post('product_reviews/bulk_action','ReviewsController@bulk_action')->name('product_reviews.bulk_action');
			Route::resource('product_reviews','ReviewsController')->except([
			    'create', 'store',

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{

	const CANCELED = 'canceled';
    const COMPLETED = 'completed';
    const ON_HOLD = 'on_hold';
    const PENDING = 'pending';
    const PENDING_PAYMENT = 'pending_payment';
    const PROCESSING = 'processing';
    const REFUNDED = 'refunded';

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'orders';


    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    public function products()
    {
        return $this->hasMany('App\OrderProduct');
    }

    public function coupon()
    {
        return $this->belongsTo('App\Entity\Coupon\Coupon')->withDefault();
    }

    public function taxes(){
    	return $this->belongsToMany('App\Entity\Tax\TaxRate', 'order_taxes')
                    ->as('order_tax')
                    ->withPivot('amount');
    }

    public function transaction()
    {
        return $this->hasOne('App\Transaction','order_id')->withDefault();
    }

    public function storeProducts($cartItem)
    {
        $orderProduct = $this->products()->create([
            'product_id' => $cartItem->associatedModel->id,
            'product_attributes' => serialize($cartItem->attributes->toArray()),
            'unit_price' => $cartItem->price,
            'qty' 		 => $cartItem->quantity,
            'line_total' => $cartItem->getPriceSumWithConditions(),
        ]);

    }

    public function attachTax($cartTax)
    {
        $this->taxes()->attach($cartTax->getAttributes()['tax_rate_id'], ['amount' => $cartTax->getValue()]);
    }

    public function getCreatedAtAttribute($value)
    {
        $date_format = get_date_format();
        //$time_format = get_time_format();
        return \Carbon\Carbon::parse($value)->format("$date_format");
    }

    public function getStatus()
    {
        if($this->status == $this::CANCELED){
            return '<span class="badge badge-danger">'.ucwords(str_replace("_"," ",$this->status)).'</span>';
        }else if($this->status == $this::COMPLETED){
            return '<span class="badge badge-success">'.ucwords(str_replace("_"," ",$this->status)).'</span>';
        }else if($this->status == $this::ON_HOLD){
            return '<span class="badge badge-warning">'.ucwords(str_replace("_"," ",$this->status)).'</span>';
        }else if($this->status == $this::PENDING){
            return '<span class="badge badge-danger">'.ucwords(str_replace("_"," ",$this->status)).'</span>';
        }else if($this->status == $this::PENDING_PAYMENT){
             return '<span class="badge badge-danger">'.ucwords(str_replace("_"," ",$this->status)).'</span>';
        }else if($this->status == $this::PROCESSING){
             return '<span class="badge badge-info">'.ucwords(str_replace("_"," ",$this->status)).'</span>';
        }else if($this->status == $this::REFUNDED){
             return '<span class="badge badge-danger">'.ucwords(str_replace("_"," ",$this->status)).'</span>';
        }
        
    }

    public function getPaymentStatus($html = true)
    {
        if(! $this->transaction()->exists()){
            return $html == true ? '<span class="badge badge-danger">'._lang('Pending').'</span>' : 0;
        }else{
            return $html == true ? '<span class="badge badge-success">'._lang('Completed').'</span>' : 1;
        }
        
    }

}

resources/views/backend/order/list.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
	<div class="col-lg-12">
		<div class="card no-export">
		    <div class="card-header">
				<span class="panel-title">{{ _lang('Order List') }}</span>
			</div>
			<div class="card-body">
				<table id="orders_table" class="table table-bordered">
					<thead>
					    <tr>
							<th>{{ _lang('Customer Name') }}</th>
							<th>{{ _lang('Email') }}</th>
							<th>{{ _lang('Total') }}</th>
							<th>{{ _lang('Status') }}</th>
							<th>{{ _lang('Payment') }}</th>
							<th class="text-center">{{ _lang('Action') }}</th>
					    </tr>
					</thead>
					<tbody>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

@endsection


@section('js-script')
<script src="{{ asset('public/backend/assets/js/datatables/orders.js') }}"></script>
@endsection

resources/views/backend/order/view.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
	<div class="col-lg-9">
		<div class="card">
		    <div class="card-header">
				<span class="panel-title">{{ _lang('View Order Details') }}</span>
			</div>
			
			<div class="card-body">

			    <div class="receipt-content">
					<div class="row">
						<div class="col-md-12">
							<div class="invoice-wrapper">

								@if($order->getPaymentStatus(false) == 1)
									<div class="payment-info">
										<div class="row">
											<div class="col-sm-6">
												<span>{{ _lang('Order ID') }}: <b>{{ $order->id }}</b></span><br>
												<span>{{ _lang('Order Date') }}: <b>{{ $order->created_at }}</b></span><br>
												<span>{{ _lang('Status') }}: <b>{!! xss_clean($order->getStatus()) !!}</b></span><br>
												
												<span><u>{{ _lang('Transaction ID') }}</u></span>
												<strong>{{ $order->transaction->transaction_id }}</strong>
											</div>
											<div class="col-sm-6 text-right">
												<span>{{ _lang('Payment Method') }}</span>
												<strong>{{ str_replace('_',' ',$order->payment_method) }}</strong>

												<span>{{ _lang('Payment Date') }}</span>
												<strong>{{ $order->transaction->created_at }}</strong>
											</div>
										</div>
									</div>
								@else
									<div class="payment-info">
										<div class="row">
											<div class="col-sm-6">
												<span>{{ _lang('Order ID') }}: <b>{{ $order->id }}</b></span><br>
												<span>{{ _lang('Order Date') }}: <b>{{ $order->created_at }}</b></span><br>
												<span>{{ _lang('Status') }}: <b>{!! xss_clean($order->getStatus()) !!}</b></span><br>
											</div>
											<div class="col-sm-6 text-right">
												<span>{{ _lang('Payment Status') }}</span>
												<strong>{!! xss_clean($order->getPaymentStatus()) !!}</strong>
											</div>
										</div>
									</div>
								@endif

								<div class="payment-details">
									<div class="row">
										<div class="col-sm-4">
											<span>{{ _lang('Billing Details') }}</span>
											<strong>
												{{ $order->customer_name }}
											</strong>
											<p>
												{{ $order->customer_email }}<br>
												{{ $order->billing_address }}<br>
												{{ $order->billing_state }}<br>
												{{ $order->billing_city }}, {{ $order->billing_post_code }} <br>
												{{ $order->billing_country }}
											</p>
										</div>

										<div class="col-sm-4">
											<span>{{ _lang('Shipping Address') }}</span>
											<p>
												{{ $order->shipping_address }}<br>
												{{ $order->shipping_state }}<br>
												{{ $order->shipping_city }}, {{ $order->shipping_post_code }} <br>
												{{ $order->shipping_country }}
											</p>
										</div>

										<div class="col-sm-4 text-right">
											<span>{{ _lang('Payment To') }}</span>
											<strong>
												{{ get_option('company_name') }}
											</strong>
											<p>
												{{ get_option('email') }}<br>
												{{ get_option('phone') }}<br>
												{!! xss_clean(get_option('address')) !!} <br>
											</p>
										</div>
									</div>
								</div>

								<div class="line-items">
									<div class="headers clearfix">
										<div class="row">
											<div class="col-6 col-md-4">{{ _lang('Description') }}</div>
											<div class="col-6 col-md-3  text-right">{{ _lang('Unit Price') }}</div>
											<div class="col-6 col-md-2">{{ _lang('Quantity') }}</div>
											<div class="col-6 col-md-3 text-right">{{ _lang('Amount') }}</div>
										</div>
									</div>
									<div class="items">
										
										@foreach($order->products as $product)
											<div class="row item">
												<div class="col-md-4 desc">
													{{ $product->product->translation->name }}
												</div>
												<div class="col-md-3 unit_price">
													{!! xss_clean(decimalPlace(convert_currency_2(1, $order->currency_rate, $product->unit_price), $order->currency)) !!}
												</div>
												<div class="col-md-2 qty">
													{{ $product->qty }}
												</div>
												<div class="col-md-3 amount">
													{!! xss_clean(decimalPlace(convert_currency_2(1, $order->currency_rate, $product->line_total), $order->currency)) !!}
												</div>
											</div>
										@endforeach

									</div>
									<div class="total text-right">
										@if($order->note != '')
											<p class="extra-notes">
												<strong>{{ _lang('Extra Notes') }}</strong>
												{{ $order->note }}
											</p>
										@endif
										<div class="field">
											{{ _lang('Sub Total') }} <span>{!! xss_clean(decimalPlace(convert_currency_2(1, $order->currency_rate, $order->sub_total), $order->currency)) !!}</span>
										</div>
										<div class="field">
											{{ _lang('Shipping') }} <span>+ {!! xss_clean(decimalPlace(convert_currency_2(1, $order->currency_rate, $order->shipping_cost), $order->currency)) !!}</span>
										</div>

										<div class="field">
											{{ _lang('Discount') }} <span>- {!! xss_clean(decimalPlace(convert_currency_2(1, $order->currency_rate, $order->discount), $order->currency)) !!}</span>
										</div>

										@foreach($order->taxes as $tax)
											<div class="field">
												{{ $tax->translation->name }} <span>+ {!! xss_clean(decimalPlace(convert_currency_2(1, $order->currency_rate, $tax->order_tax->amount), $order->currency)) !!}</span>
											</div>
										@endforeach

										<div class="field grand-total">
											{{ _lang('Total') }} <span>{!! xss_clean(decimalPlace(convert_currency_2(1, $order->currency_rate, $order->total), $order->currency)) !!}</span>
										</div>
									</div>

								</div>
							</div>
						</div>
					</div>
				</div>  

			</div>
	    </div>
	</div>

	<div class="col-lg-3">
		<div class="card">
			<div class="card-header">
				<span class="panel-title">{{ _lang('Order Actions') }}</span>
			</div>
			<div class="card-body">
				<form action="{{ action('OrderController@update', $order->id) }}" method="post" id="order-update-form">
					
					@csrf
					<input name="_method" type="hidden" value="PATCH">

					<div class="col-md-12">
				        <div class="form-group">
					        <label class="control-label">{{ _lang('Order Status') }}</label>						
					        <select class="form-control auto-select" data-selected="{{ $order->status }}" name="status" required>		
								<option value="pending_payment">{{ _lang('Pending Payment') }}</option>
								<option value="pending">{{ _lang('Pending') }}</option>
								<option value="completed">{{ _lang('Completed') }}</option>
								<option value="on_hold">{{ _lang('On Hold') }}</option>
								<option value="processing">{{ _lang('Processing') }}</option>
								<option value="refunded">{{ _lang('Refunded') }}</option>	
								<option value="canceled">{{ _lang('Canceled') }}</option>	
							</select>
						</div>
				    </div>

				   @if($order->getPaymentStatus(false) == 0)
					   <div class="col-md-12">
					        <div class="form-group">
						        <label class="control-label">{{ _lang('Payment Status') }}</label>						
						        <select class="form-control"  name="payment_status" id="payment_status" required>
									<option value="pending" {{ $order->getPaymentStatus(false) == 0 ? 'selected' : '' }}>{{ _lang('Pending') }}</option>
									<option value="completed" {{ $order->getPaymentStatus(false) == 1 ? 'selected' : '' }}>{{ _lang('Completed') }}</option>	
								</select>
							</div>
					    </div>

					    <div class="col-md-12 d-none transaction_id">
					        <div class="form-group">
						        <label class="control-label">{{ _lang('Payment Method') }}</label>						
						        <select class="form-control auto-select" data-selected="{{ $order->payment_method }}" name="payment_method">		
						        	@if($order->payment_method == '')
										<option value="">{{ _lang('Select Method') }}</option>
										<option value="Cash_On_Deliver">{{ _lang('Cash On Deliver') }}</option>
										<option value="Bank_Transfer">{{ _lang('Bank Transfer') }}</option>
									@else
										<option value="{{ $order->payment_method }}">{{ str_replace('_',' ',$order->payment_method) }}</option>
									@endif
								</select>
							</div>
					    </div>

					    <div class="col-md-12 d-none transaction_id">
					        <div class="form-group">
						        <label class="control-label">{{ _lang('Transaction ID') }}</label>						
						        <input type="text" name="transaction_id" class="form-control">
							</div>
					    </div>
				    @endif


				    <div class="col-md-12">
						<div class="form-group">
							<button type="submit" class="btn btn-warning btn-block">{{ _lang('Update Order') }}</button>
						</div>
					</div>


				</form>
			</div>
		</div>
	</div>
</div>
@endsection