routes/web.php
	Route::get('/apply_tax/{shipping_state?}/{billing_state?}', 'Website\CheckoutController@apply_tax');
	Route::post('/make_order', 'Website\CheckoutController@make_order');
	Route::get('/payment/{order_id}', 'Website\CheckoutController@payment');

	//Get Variation Price
	Route::post('products/get_variation_price/{product_id}','ProductController@get_variation_price');

	//Add to Cart
	Route::post('/add_to_cart/{product_id}', 'Website\CartController@add_to_cart');
	Route::post('/update_cart', 'Website\CartController@update_cart');
	Route::post('/apply_coupon', 'Website\CartController@apply_coupon');
	Route::get('/remove_coupon/{name}', 'Website\CartController@remove_coupon');
	Route::get('/remove_cart_item/{id}', 'Website\CartController@remove_cart_item');
	Route::get('/shipping_method/{name}', 'Website\CartController@shipping_method');

	//Payment Gateways
	Route::get('gateway/paypal_payment_authorize/{paypal_order_id}/{order_id}', 'Website\GatewayController@paypal_payment_authorize');
	Route::post('gateway/stripe_payment_authorize/{order_id}', 'Website\GatewayController@stripe_payment_authorize');
	Route::post('gateway/razorpay_payment_authorize/{order_id}', 'Website\GatewayController@razorpay_payment_authorize');
	Route::get('gateway/paystack_payment_authorize/{order_id}/{reference}', 'Website\GatewayController@paystack_payment_authorize');
	Route::get('gateway/confirm_order/{type}/{order_id}', 'Website\GatewayController@confirm_order'); //This route is for manual payment

	
	Route::group(['prefix'=> 'admin'], function () {
//	    Route::get('/', function(){
//	    	return redirect('admin/login');
//	    });
	    Auth::routes(['verify' => true]);
	});
  
	Route::get('/logout', 'Auth\LoginController@logout');
	Route::get('/{slug?}', 'Website\WebsiteController@index');
	
	Route::group(['middleware' => ['auth','verified'], 'prefix'=> 'admin'], function () {


	    //Contact
        Route::get('/contact_us', 'ContactUsController@index')->name('contact_us');

        //Slide

        Route::get('/slide', 'SlideController@index')->name('slide.index');
        Route::get('/slide/create', 'SlideController@create')->name('slide.create');
        Route::post('/slide/store','SlideController@store')->name('slide.store');
        Route::get('/slide/edit/{id}','SlideController@edit')->name('slide.edit');
        Route::post('/slide/update','SlideController@update')->name('slide.update');
        Route::delete('/slide/destroy/{id}','SlideController@destroy')->name('slide.destroy');

        //Product

        Route::get('products/search','ProductController@search')->name('products.search');
		Route::get('dashboard', 'DashboardController@index')->middleware('groupPermission:admin,user,customer');
		
		//Profile Controller
		Route::get('profile/edit', 'ProfileController@edit')->middleware('groupPermission:admin,user');
		Route::post('profile/update', 'ProfileController@update')->middleware('groupPermission:admin,user');
		Route::get('profile/change_password', 'ProfileController@change_password')->middleware('groupPermission:admin,user');
		Route::post('profile/update_password', 'ProfileController@update_password')->middleware('groupPermission:admin,user');
		

		/** Admin Only Route **/
		Route::group(['middleware' => ['admin']], function () {


			//User Management
			Route::resource('users','UserController');

			//User Roles
			Route::resource('roles','RoleController');
			
			//Permission Controller
		    Route::get('permission/control/{user_id?}', 'PermissionController@index')->name('permission.index');
			Route::post('permission/store', 'PermissionController@store')->name('permission.store');

			
			//Language Controller
			Route::resource('languages','LanguageController');	
			
			//Utility Controller
			Route::match(['get', 'post'],'general_settings/{store?}', 'UtilityController@settings')->name('settings.update_settings');
			Route::match(['get', 'post'],'theme_option/{page?}/{store?}', 'UtilityController@theme_option')->name('theme_option.update');
			Route::post('upload_logo', 'UtilityController@upload_logo')->name('settings.uplaod_logo');
			Route::get('database_backup_list', 'UtilityController@database_backup_list')->name('database_backups.list');
			Route::get('create_database_backup', 'UtilityController@create_database_backup')->name('database_backups.create');
			Route::delete('destroy_database_backup/{id}', 'UtilityController@destroy_database_backup');
			Route::get('download_database_backup/{id}', 'UtilityController@download_database_backup')->name('database_backups.download');
			Route::post('remove_cache', 'UtilityController@remove_cache')->name('settings.remove_cache');

			//Email Template
			Route::resource('email_templates','EmailTemplateController')->only([
				'index', 'show', 'edit', 'update'
			]);

			//Shipping Methods
			Route::get('shipping_methods', 'UtilityController@shipping_methods')->name('settings.shipping_methods');
			
			
		});

        /** Dynamic Permission **/
		Route::group(['middleware' => ['permission']], function () {

			Route::get('dashboard/total_sales_widget', 'DashboardController@total_sales_widget')->name('dashboard.total_sales_widget');
			Route::get('dashboard/current_day_sales_widget', 'DashboardController@current_day_sales_widget')->name('dashboard.current_day_sales_widget');
			Route::get('dashboard/pending_order_widget', 'DashboardController@pending_order_widget')->name('dashboard.pending_order_widget');
			Route::get('dashboard/total_product_widget', 'DashboardController@total_product_widget')->name('dashboard.total_product_widget');
			Route::get('dashboard/weekly_sales_widget', 'DashboardController@weekly_sales_widget')->name('dashboard.weekly_sales_widget');
			Route::get('dashboard/top_view_items_widget', 'DashboardController@top_view_items_widget')->name('dashboard.top_view_items_widget');
			Route::get('dashboard/recent_order_widget', 'DashboardController@recent_order_widget')->name('dashboard.recent_order_widget');
			
			//Media Controller
			Route::get('media/get_table_data/{type?}/{select_type?}','MediaController@get_table_data');
			Route::resource('media','MediaController')->except([
				'edit', 'update'
			]);

			//Order Controller
			Route::get('orders/get_table_data','OrderController@get_table_data');
			Route::resource('orders','OrderController')->except([
			    'create', 'store', 'edit'
			]);

			//Transaction Controller
			Route::get('transactions/get_table_data','TransactionController@get_table_data');
			Route::get('transactions','TransactionController@index')->name('transactions.index');

			//Product Controller
			Route::post('products/generate_variations','ProductController@generate_variations');
			Route::get('products/get_table_data','ProductController@get_table_data');

			Route::resource('products','ProductController');

			//Comments Controller
			Route::get('product_comments/get_table_data','CommentController@get_table_data');
			Route::get('product_comments/destroy/{id}','CommentController@destroy')->name('product_comments.destroy');
			Route::resource('product_comments','CommentController')->only([
			    'index', 'show'
			]);

			//Reviews Controller
			Route::get('product_reviews/get_table_data','ReviewsController@get_table_data');
			Route::post('product_reviews/bulk_action','ReviewsController@bulk_action')->name('product_reviews.bulk_action');
			Route::resource('product_reviews','ReviewsController')->except([
			    'create', 'store',
			]);

			//Category Controller
			Route::resource('category','CategoryController');

			//Brand Controller
			Route::resource('brands','BrandController');

			//Tag Controller
			Route::resource('tags','TagController');

			//Coupon Controller
			Route::resource('coupons','CouponController');

			//Customer Controller
			Route::resource('customers','CustomerController');

			//Currency Controller
			Route::resource('currency','CurrencyController');

			//Tax Vontroller
			Route::get('taxes/get_states/{country_id}','TaxController@get_states');
			Route::resource('taxes','TaxController');

			//Page Controller
			Route::resource('pages','PageController');

			//Navigation Controller
			Route::resource('navigations','NavigationController');
			Route::post('navigations/store_sorting','NavigationController@store_sorting');
			Route::get('navigation_items/{navigation_id}/create','NavigationItemController@create')->name('navigation_items.create');
			Route::post('navigation_items/store/{navigation_id}','NavigationItemController@store')->name('navigation_items.store');
			Route::get('navigation_items/edit/{id}','NavigationItemController@edit')->name('navigation_items.edit');
			Route::patch('navigation_items/update/{id}','NavigationItemController@update')->name('navigation_items.update');
			Route::get('navigation_items/destroy/{id}','NavigationItemController@destroy')->name('navigation_items.destroy');

		});
	
	});

});

//Socila Login
Route::get('/login/{provider}', 'Auth\SocialController@redirect');
Route::get('/login/{provider}/callback','Auth\SocialController@callback');

//Get State By Country
Route::get('get_states/{country_id}','Website\WebsiteController@get_states');

//Search Products
Route::get('shop/search_products','Website\WebsiteController@search_products');

//Ajax Select2 Controller
Route::get('ajax/get_table_data','Select2Controller@get_table_data');

//Change Language
Route::get('select_language/{language}','UtilityController@select_language');

Route::get('installation/start', 'Install\InstallController@index');
Route::get('install/database', 'Install\InstallController@database');
Route::post('install/process_install', 'Install\InstallController@process_install');
Route::get('install/create_user', 'Install\InstallController@create_user');
Route::post('install/store_user', 'Install\InstallController@store_user');
Route::get('install/system_settings', 'Install\InstallController@system_settings');
Route::post('install/finish', 'Install\InstallController@final_touch');

app/Currency.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Currency extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'currency';

}

app/Http/Controllers/CurrencyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Currency;
use Validator;

class CurrencyController extends Controller
{
	
	/**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        date_default_timezone_set(get_option('timezone','Asia/Dhaka'));
    }
	
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $currencys = Currency::all()->sortByDesc("id");
        return view('backend.currency.list',compact('currencys'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        if( ! $request->ajax()){
           return view('backend.currency.create');
        }else{
           return view('backend.currency.modal.create');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {	
        $validator = Validator::make($request->all(), [
            'name' => 'required',
			'base_currency' => '',
			'exchange_rate' => 'required|numeric',
			'status' => 'required',
        ]);

        if ($validator->fails()) {
            if($request->ajax()){ 
                return response()->json(['result'=>'error','message'=>$validator->errors()->all()]);
            }else{
                return redirect()->route('currency.create')
                	             ->withErrors($validator)
                	             ->withInput();
            }			
        }

        if($request->input('base_currency') == '1'){
            $currency = Currency::where('base_currency','1')->first();
            if($currency){
                $currency->base_currency = 0;
                $currency->save();
            }
        }
	     

        $currency = new Currency();
        $currency->name = $request->input('name');
		$currency->base_currency = $request->input('base_currency');
		$currency->exchange_rate = $request->input('exchange_rate');
		$currency->status = $request->input('status');

        $currency->save();

        \Cache::forget('currency');

        //Prefix output
        $currency->base_currency = $currency->base_currency == 1 ? _lang('Yes') : _lang('No');
        $currency->status = $currency->status == 1 ? _lang('Active') : _lang('InActive');

        if(! $request->ajax()){
           return redirect()->route('currency.create')->with('success', _lang('Saved Sucessfully'));
        }else{
           return response()->json(['result'=>'success','action'=>'store','message'=>_lang('Saved Sucessfully'),'data'=>$currency, 'table' => '#currency_table']);
        }
        
   }
	

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request,$id)
    {
        $currency = Currency::find($id);
        if(! $request->ajax()){
            return view('backend.currency.view',compact('currency','id'));
        }else{
            return view('backend.currency.modal.view',compact('currency','id'));
        } 
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request,$id)
    {
        $currency = Currency::find($id);
        if(! $request->ajax()){
            return view('backend.currency.edit',compact('currency','id'));
        }else{
            return view('backend.currency.modal.edit',compact('currency','id'));
        }  
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
		$validator = Validator::make($request->all(), [
			'name' => 'required',
			'base_currency' => '',
			'exchange_rate' => 'required|numeric',
			'status' => 'required',
		]);

		if ($validator->fails()) {
			if($request->ajax()){ 
				return response()->json(['result'=>'error','message'=>$validator->errors()->all()]);
			}else{
				return redirect()->route('currency.edit', $id)
							->withErrors($validator)
							->withInput();
			}			
		}

        if($request->input('base_currency') == '1'){
            $base_currency = Currency::where('base_currency','1')->first();
            if($base_currency){
                $base_currency->base_currency = 0;
                $base_currency->save();
            }
        }   
	 	
		
        $currency = Currency::find($id);
		$currency->name = $request->input('name');
		$currency->base_currency = $request->input('base_currency');
		$currency->exchange_rate = $request->input('exchange_rate');
		$currency->status = $request->input('status');
	
        $currency->save();

        \Cache::forget('currency');

        //Prefix output
        $currency->base_currency = $currency->base_currency == 1 ? _lang('Yes') : _lang('No');
        $currency->status = $currency->status == 1 ? _lang('Active') : _lang('InActive');
		
		if(! $request->ajax()){
           return redirect()->route('currency.index')->with('success', _lang('Updated Sucessfully'));
        }else{
		   return response()->json(['result'=>'success','action'=>'update', 'message'=>_lang('Updated Sucessfully'),'data'=>$currency, 'table' => '#currency_table']);
		}
	    
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $currency = Currency::find($id);
        $currency->delete();
        return redirect()->route('currency.index')->with('success',_lang('Deleted Sucessfully'));
    }
}

resources/views/backend/currency/create.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
	<div class="col-lg-6">
		<div class="card">
			<div class="card-header bg-primary text-white">
				<span class="panel-title">{{ _lang('Add Currency') }}</span>
			</div>
			<div class="card-body">
			    <form method="post" class="validate" autocomplete="off" action="{{ route('currency.store') }}" enctype="multipart/form-data">
					{{ csrf_field() }}
					<div class="row">
						<div class="col-md-12">
					        <div class="form-group">
						        <label class="control-label">{{ _lang('Name') }}</label>						
						        <select class="form-control auto-select select2" data-selected="{{ old('name') }}" name="name" required>
					                <option value="">{{ _lang('Select One') }}</option>
									{{ get_currency_list() }}
								</select>
							</div>
					    </div>

						<div class="col-md-12">
					        <div class="form-group">
						        <label class="control-label">{{ _lang('Base Currency') }}</label>						
						        <select class="form-control auto-select" data-selected="{{ old('base_currency') }}" name="base_currency">
					                <option value="">{{ _lang('Select One') }}</option>
									<option value="0">{{ _lang('No') }}</option>
									<option value="1">{{ _lang('Yes') }}</option>
								</select>
							</div>
					    </div>

						<div class="col-md-12">
					        <div class="form-group">
						        <label class="control-label">{{ _lang('Exchange Rate') }}</label>						
						        <input type="text" class="form-control" name="exchange_rate" value="{{ old('exchange_rate') }}" required>
					        </div>
					    </div>

						<div class="col-md-12">
					        <div class="form-group">
						        <label class="control-label">{{ _lang('Status') }}</label>						
						        <select class="form-control auto-select" data-selected="{{ old('status',1) }}" name="status" required>
									<option value="1">{{ _lang('Active') }}</option>
									<option value="0">{{ _lang('InActive') }}</option>
								</select>
							</div>
					    </div>

							
						<div class="col-md-12">
							<div class="form-group">
								<button type="submit" class="btn btn-primary">{{ _lang('Save') }}</button>
							</div>
						</div>
					</div>			
			    </form>
			</div>
		</div>
    </div>
</div>
@endsection

resources/views/backend/currency/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
	<div class="col-lg-6">
		<div class="card">
			<div class="card-header bg-primary text-white">
				<span class="panel-title">{{ _lang('Update Currency') }}</span>
			</div>
			<div class="card-body">
				<form method="post" class="validate" autocomplete="off" action="{{ action('CurrencyController@update', $id) }}" enctype="multipart/form-data">
					{{ csrf_field()}}
					<input name="_method" type="hidden" value="PATCH">				
					<div class="row">
						<div class="col-md-12">
							    <div class="form-group">
								    <label class="control-label">{{ _lang('Name') }}</label>						
								    <select class="form-control auto-select select2" data-selected="{{ $currency->name }}" name="name" required>
						                <option value="">{{ _lang('Select One') }}</option>
										{{ get_currency_list() }}
								    </select>
							    </div>
							</div>

							<div class="col-md-12">
							    <div class="form-group">
								    <label class="control-label">{{ _lang('Base Currency') }}</label>						
								    <select class="form-control auto-select" data-selected="{{ $currency->base_currency }}" name="base_currency">
						                <option value="">{{ _lang('Select One') }}</option>
										<option value="0">{{ _lang('No') }}</option>
										<option value="1">{{ _lang('Yes') }}</option>
								    </select>
							    </div>
							</div>

							<div class="col-md-12">
							    <div class="form-group">
								   <label class="control-label">{{ _lang('Exchange Rate') }}</label>						
								   <input type="text" class="form-control" name="exchange_rate" value="{{ $currency->exchange_rate }}" required>
							    </div>
							</div>

							<div class="col-md-12">
							    <div class="form-group">
								    <label class="control-label">{{ _lang('Status') }}</label>						
								    <select class="form-control auto-select" data-selected="{{ $currency->status }}" name="status" required>
										<option value="1">{{ _lang('Active') }}</option>
										<option value="0">{{ _lang('InActive') }}</option>
								    </select>
							    </div>
							</div>

							
						<div class="col-md-12">
							<div class="form-group">
								<button type="submit" class="btn btn-primary">{{ _lang('Update') }}</button>
							</div>
						</div>	
					</div>	
				</form>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/backend/currency/list.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
	<div class="col-lg-12">
		<div class="alert alert-warning">
			<strong>{{ _lang('Do not change base currecny once you made any transactions otherwise your calculation will be wrong !') }}</strong>
		</div>
		
		<div class="alert alert-info">
			<strong>{{ _lang('Base currency exchange rate will be always 1.00') }}</strong>
		</div>
		
		<div class="card no-export">
		    <div class="card-header d-flex align-items-center">
				<span class="panel-title">{{ _lang('Currency List') }}</span>
				<a class="btn btn-primary btn-xs ml-auto ajax-modal" data-title="{{ _lang('Add Currency') }}" href="{{ route('currency.create') }}">{{ _lang('Add New') }}</a>
			</div>
			<div class="card-body">
				<table id="currency_table" class="table table-bordered data-table">
					<thead>
					    <tr>
						    <th>{{ _lang('Name') }}</th>
							<th>{{ _lang('Base Currency') }}</th>
							<th>{{ _lang('Exchange Rate') }}</th>
							<th>{{ _lang('Status') }}</th>
							<th class="text-center">{{ _lang('Action') }}</th>
					    </tr>
					</thead>
					<tbody>
					    @foreach($currencys as $currency)
					    <tr data-id="row_{{ $currency->id }}">
							<td class='name'>{{ $currency->name }}</td>
							<td class='base_currency'>{{ $currency->base_currency == 1 ? _lang('Yes') : _lang('No') }}</td>
							<td class='exchange_rate'>{{ $currency->exchange_rate }}</td>
							<td class='status'>{{ $currency->status == 1 ? _lang('Active') : _lang('InActive') }}</td>
							
							<td class="text-center">
								<div class="dropdown">
								  <button class="btn btn-light dropdown-toggle btn-xs" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								  {{ _lang('Action') }}
								  <i class="fas fa-angle-down"></i>
								  </button>
								  <form action="{{ action('CurrencyController@destroy', $currency['id']) }}" method="post">
									{{ csrf_field() }}
									<input name="_method" type="hidden" value="DELETE">
									
									<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
										<a href="{{ action('CurrencyController@edit', $currency['id']) }}" data-title="{{ _lang('Update Currency') }}" class="dropdown-item dropdown-edit ajax-modal"><i class="mdi mdi-pencil"></i> {{ _lang('Edit') }}</a>
										<a href="{{ action('CurrencyController@show', $currency['id']) }}" data-title="{{ _lang('View Currency') }}" class="dropdown-item dropdown-view ajax-modal"><i class="mdi mdi-eye"></i> {{ _lang('View') }}</a>
										<button class="btn-remove dropdown-item" type="submit"><i class="mdi mdi-delete"></i> {{ _lang('Delete') }}</button>
									</div>
								  </form>
								</div>
							</td>
					    </tr>
					    @endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/backend/currency/view.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
	<div class="col-lg-6">
		<div class="card">
		    <div class="card-header bg-primary text-white">
				<span class="panel-title">{{ _lang('View Currency') }}</span>
			</div>
			
			<div class="card-body">
				<table class="table table-bordered">
					<tr><td>{{ _lang('Name') }}</td><td>{{ $currency->name }}</td></tr>
					<tr><td>{{ _lang('Is Base Currency') }}</td><td>{{ $currency->base_currency == 1 ? _lang('Yes') : _lang('No') }}</td></tr>
					<tr><td>{{ _lang('Exchange Rate') }}</td><td>{{ $currency->exchange_rate }}</td></tr>
					<tr><td>{{ _lang('Status') }}</td><td>{{ $currency->status == 1 ? _lang('Active') : _lang('InActive')  }}</td></tr>
				</table>
			</div>
	    </div>
	</div>
</div>
@endsection