routes/web.php
	Route::get('/apply_tax/{shipping_state?}/{billing_state?}', 'Website\CheckoutController@apply_tax');
	Route::post('/make_order', 'Website\CheckoutController@make_order');
	Route::get('/payment/{order_id}', 'Website\CheckoutController@payment');

	//Get Variation Price
	Route::post('products/get_variation_price/{product_id}','ProductController@get_variation_price');

	//Add to Cart
	Route::post('/add_to_cart/{product_id}', 'Website\CartController@add_to_cart');
	Route::post('/update_cart', 'Website\CartController@update_cart');
	Route::post('/apply_coupon', 'Website\CartController@apply_coupon');
	Route::get('/remove_coupon/{name}', 'Website\CartController@remove_coupon');
	Route::get('/remove_cart_item/{id}', 'Website\CartController@remove_cart_item');
	Route::get('/shipping_method/{name}', 'Website\CartController@shipping_method');

	//Payment Gateways
	Route::get('gateway/paypal_payment_authorize/{paypal_order_id}/{order_id}', 'Website\GatewayController@paypal_payment_authorize');
	Route::post('gateway/stripe_payment_authorize/{order_id}', 'Website\GatewayController@stripe_payment_authorize');
	Route::post('gateway/razorpay_payment_authorize/{order_id}', 'Website\GatewayController@razorpay_payment_authorize');
	Route::get('gateway/paystack_payment_authorize/{order_id}/{reference}', 'Website\GatewayController@paystack_payment_authorize');
	Route::get('gateway/confirm_order/{type}/{order_id}', 'Website\GatewayController@confirm_order'); //This route is for manual payment

	
	Route::group(['prefix'=> 'admin'], function () {
//	    Route::get('/', function(){
//	    	return redirect('admin/login');
//	    });
	    Auth::routes(['verify' => true]);
	});
  
	Route::get('/logout', 'Auth\LoginController@logout');
	Route::get('/{slug?}', 'Website\WebsiteController@index');
	
	Route::group(['middleware' => ['auth','verified'], 'prefix'=> 'admin'], function () {


	    //Contact
        Route::get('/contact_us', 'ContactUsController@index')->name('contact_us');

        //Slide

        Route::get('/slide', 'SlideController@index')->name('slide.index');
        Route::get('/slide/create', 'SlideController@create')->name('slide.create');
        Route::post('/slide/store','SlideController@store')->name('slide.store');
        Route::get('/slide/edit/{id}','SlideController@edit')->name('slide.edit');
        Route::post('/slide/update','SlideController@update')->name('slide.update');
        Route::delete('/slide/destroy/{id}','SlideController@destroy')->name('slide.destroy');

        //Product

        Route::get('products/search','ProductController@search')->name('products.search');
		Route::get('dashboard', 'DashboardController@index')->middleware('groupPermission:admin,user,customer');
		
		//Profile Controller
		Route::get('profile/edit', 'ProfileController@edit')->middleware('groupPermission:admin,user');
		Route::post('profile/update', 'ProfileController@update')->middleware('groupPermission:admin,user');
		Route::get('profile/change_password', 'ProfileController@change_password')->middleware('groupPermission:admin,user');
		Route::post('profile/update_password', 'ProfileController@update_password')->middleware('groupPermission:admin,user');
		

		/** Admin Only Route **/
		Route::group(['middleware' => ['admin']], function () {


			//User Management
			Route::resource('users','UserController');

			//User Roles
			Route::resource('roles','RoleController');
			
			//Permission Controller
		    Route::get('permission/control/{user_id?}', 'PermissionController@index')->name('permission.index');
			Route::post('permission/store', 'PermissionController@store')->name('permission.store');

			
			//Language Controller
			Route::resource('languages','LanguageController');	
			
			//Utility Controller
			Route::match(['get', 'post'],'general_settings/{store?}', 'UtilityController@settings')->name('settings.update_settings');
			Route::match(['get', 'post'],'theme_option/{page?}/{store?}', 'UtilityController@theme_option')->name('theme_option.update');
			Route::post('upload_logo', 'UtilityController@upload_logo')->name('settings.uplaod_logo');
			Route::get('database_backup_list', 'UtilityController@database_backup_list')->name('database_backups.list');
			Route::get('create_database_backup', 'UtilityController@create_database_backup')->name('database_backups.create');
			Route::delete('destroy_database_backup/{id}', 'UtilityController@destroy_database_backup');
			Route::get('download_database_backup/{id}', 'UtilityController@download_database_backup')->name('database_backups.download');
			Route::post('remove_cache', 'UtilityController@remove_cache')->name('settings.remove_cache');

			//Email Template
			Route::resource('email_templates','EmailTemplateController')->only([
				'index', 'show', 'edit', 'update'
			]);

			//Shipping Methods
			Route::get('shipping_methods', 'UtilityController@shipping_methods')->name('settings.shipping_methods');
			
			
		});

        /** Dynamic Permission **/
		Route::group(['middleware' => ['permission']], function () {

			Route::get('dashboard/total_sales_widget', 'DashboardController@total_sales_widget')->name('dashboard.total_sales_widget');
			Route::get('dashboard/current_day_sales_widget', 'DashboardController@current_day_sales_widget')->name('dashboard.current_day_sales_widget');
			Route::get('dashboard/pending_order_widget', 'DashboardController@pending_order_widget')->name('dashboard.pending_order_widget');
			Route::get('dashboard/total_product_widget', 'DashboardController@total_product_widget')->name('dashboard.total_product_widget');
			Route::get('dashboard/weekly_sales_widget', 'DashboardController@weekly_sales_widget')->name('dashboard.weekly_sales_widget');
			Route::get('dashboard/top_view_items_widget', 'DashboardController@top_view_items_widget')->name('dashboard.top_view_items_widget');
			Route::get('dashboard/recent_order_widget', 'DashboardController@recent_order_widget')->name('dashboard.recent_order_widget');
			
			//Media Controller
			Route::get('media/get_table_data/{type?}/{select_type?}','MediaController@get_table_data');
			Route::resource('media','MediaController')->except([
				'edit', 'update'
			]);

			//Order Controller
			Route::get('orders/get_table_data','OrderController@get_table_data');
			Route::resource('orders','OrderController')->except([
			    'create', 'store', 'edit'
			]);

			//Transaction Controller
			Route::get('transactions/get_table_data','TransactionController@get_table_data');
			Route::get('transactions','TransactionController@index')->name('transactions.index');

			//Product Controller
			Route::post('products/generate_variations','ProductController@generate_variations');
			Route::get('products/get_table_data','ProductController@get_table_data');

			Route::resource('products','ProductController');

			//Comments Controller
			Route::get('product_comments/get_table_data','CommentController@get_table_data');
			Route::get('product_comments/destroy/{id}','CommentController@destroy')->name('product_comments.destroy');
			Route::resource('product_comments','CommentController')->only([
			    'index', 'show'
			]);

			//Reviews Controller
			Route::get('product_reviews/get_table_data','ReviewsController@get_table_data');
			Route::post('product_reviews/bulk_action','ReviewsController@bulk_action')->name('product_reviews.bulk_action');
			Route::resource('product_reviews','ReviewsController')->except([
			    'create', 'store',
			]);

			//Category Controller
			Route::resource('category','CategoryController');

			//Brand Controller
			Route::resource('brands','BrandController');

			//Tag Controller
			Route::resource('tags','TagController');

			//Coupon Controller
			Route::resource('coupons','CouponController');

			//Customer Controller
			Route::resource('customers','CustomerController');

			//Currency Controller
			Route::resource('currency','CurrencyController');

			//Tax Vontroller
			Route::get('taxes/get_states/{country_id}','TaxController@get_states');
			Route::resource('taxes','TaxController');

			//Page Controller
			Route::resource('pages','PageController');

			//Navigation Controller
			Route::resource('navigations','NavigationController');
			Route::post('navigations/store_sorting','NavigationController@store_sorting');
			Route::get('navigation_items/{navigation_id}/create','NavigationItemController@create')->name('navigation_items.create');
			Route::post('navigation_items/store/{navigation_id}','NavigationItemController@store')->name('navigation_items.store');
			Route::get('navigation_items/edit/{id}','NavigationItemController@edit')->name('navigation_items.edit');
			Route::patch('navigation_items/update/{id}','NavigationItemController@update')->name('navigation_items.update');
			Route::get('navigation_items/destroy/{id}','NavigationItemController@destroy')->name('navigation_items.destroy');

		});
	
	});

});

//Socila Login
Route::get('/login/{provider}', 'Auth\SocialController@redirect');
Route::get('/login/{provider}/callback','Auth\SocialController@callback');

//Get State By Country
Route::get('get_states/{country_id}','Website\WebsiteController@get_states');

//Search Products
Route::get('shop/search_products','Website\WebsiteController@search_products');

//Ajax Select2 Controller
Route::get('ajax/get_table_data','Select2Controller@get_table_data');

//Change Language
Route::get('select_language/{language}','UtilityController@select_language');

Route::get('installation/start', 'Install\InstallController@index');
Route::get('install/database', 'Install\InstallController@database');
Route::post('install/process_install', 'Install\InstallController@process_install');
Route::get('install/create_user', 'Install\InstallController@create_user');
Route::post('install/store_user', 'Install\InstallController@store_user');
Route::get('install/system_settings', 'Install\InstallController@system_settings');
Route::post('install/finish', 'Install\InstallController@final_touch');

app/EmailTemplate.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class EmailTemplate extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'email_templates';
}

app/Http/Controllers/EmailTemplateController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\EmailTemplate;
use Validator;
use Illuminate\Validation\Rule;

class EmailTemplateController extends Controller
{	
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $emailtemplates = EmailTemplate::all();
        return view('backend.administration.email_template.list',compact('emailtemplates'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
		if( ! $request->ajax()){
		   return view('backend.administration.email_template.create');
		}else{
           return view('backend.administration.email_template.modal.create');
		}
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {	
		$validator = Validator::make($request->all(), [
			'name' => 'required:unique:email_templates',
			'subject' => 'required',
			'body' => 'required'
		]);
		
		if ($validator->fails()) {
			if($request->ajax()){ 
			    return response()->json(['result'=>'error','message'=>$validator->errors()->all()]);
			}else{
				return redirect('email_templates/create')
							->withErrors($validator)
							->withInput();
			}			
		}
			
	    
		
        $emailtemplate= new EmailTemplate();
	    $emailtemplate->name = $request->input('name');
		$emailtemplate->subject = $request->input('subject');
		$emailtemplate->body = $request->input('body');
	
        $emailtemplate->save();
        
		if(! $request->ajax()){
           return redirect()->route('email_templates.index')->with('success', _lang('Saved Sucessfully'));
        }else{
		   return response()->json(['result'=>'success','action'=>'store','message'=>_lang('Saved Sucessfully'),'data'=>$emailtemplate]);
		}
        
   }
	

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request,$id)
    {
        $emailtemplate = EmailTemplate::find($id);
		if(! $request->ajax()){
		    return view('backend.administration.email_template.view',compact('emailtemplate','id'));
		}else{
			return view('backend.administration.email_template.modal.view',compact('emailtemplate','id'));
		} 
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request,$id)
    {
        $vars = array(
            'welcome_email'     =>  '{name} {email} {phone}',
            'order_placed'      =>  '{name} {order_id} {order_status} {payment_method} {payment_status}',
            'order_processing'  =>  '{name} {order_id} {order_status} {payment_method} {payment_status}',
            'order_completed'   =>  '{name} {order_id} {order_status} {payment_method} {payment_status}',
            'order_canceled'    =>  '{name} {order_id} {order_status} {payment_method} {payment_status}',
            'order_on_hold'     =>  '{name} {order_id} {order_status} {payment_method} {payment_status}',
            'order_refunded'    =>  '{name} {order_id} {order_status} {payment_method} {payment_status}',
        );
        $emailtemplate = EmailTemplate::find($id);

		if(! $request->ajax()){
		   return view('backend.administration.email_template.edit',compact('emailtemplate','id','vars'));
		}else{
           return view('backend.administration.email_template.modal.edit',compact('emailtemplate','id','vars'));
		}  
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
		$validator = Validator::make($request->all(), [
			'name' => '',
			'subject' => 'required',
			'body' => 'required'
		]);
		
		if ($validator->fails()) {
			if($request->ajax()){ 
			    return response()->json(['result'=>'error','message'=>$validator->errors()->all()]);
			}else{
				return redirect()->route('email_templates.edit', $id)
							->withErrors($validator)
							->withInput();
			}			
		}
	
        	
		
        $emailtemplate = EmailTemplate::find($id);
		$emailtemplate->subject = $request->input('subject');
		$emailtemplate->body = $request->input('body');
	
        $emailtemplate->save();
		
		if(! $request->ajax()){
           return redirect()->route('email_templates.index')->with('success', _lang('Updated Sucessfully'));
        }else{
		   return response()->json(['result'=>'success','action'=>'update', 'message'=>_lang('Updated Sucessfully'),'data'=>$emailtemplate]);
		}
	    
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    /*public function destroy($id)
    {
        $emailtemplate = EmailTemplate::find($id);
        $emailtemplate->delete();
        return redirect()->route('email_templates.index')->with('success',_lang('Removed Sucessfully'));
    }*/
}

resources/views/backend/administration/email_template/create.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
	<div class="col-12">
		<div class="card">
			<div class="card-body">
				<form method="post" class="validate" autocomplete="off" action="{{ route('email_templates.store') }}" enctype="multipart/form-data">
					{{ csrf_field() }}
					
					<div class="col-md-12">
					  	<div class="form-group">
							<label class="control-label">{{ _lang('Name') }}</label>						
							<input type="text" class="form-control" name="name" value="{{ old('name') }}">
					  	</div>
					</div>

					<div class="col-md-12">
					 	<div class="form-group">
							<label class="control-label">{{ _lang('Subject') }}</label>						
							<input type="text" class="form-control" name="subject" value="{{ old('subject') }}" required>
					  	</div>
					</div>

					<div class="col-md-12">
					  	<div class="form-group">
							<label class="control-label">{{ _lang('Body') }}</label>						
							<textarea class="form-control summernote" name="body">{{ old('body') }}</textarea>
					  	</div>
					</div>

							
					<div class="form-group">
					  	<div class="col-md-12">
					    	<button type="reset" class="btn btn-danger">{{ _lang('Reset') }}</button>
							<button type="submit" class="btn btn-primary">{{ _lang('Save') }}</button>
					  	</div>
					</div>
				</form>
			</div>
	  	</div>
	</div>
</div>
@endsection

resources/views/backend/administration/email_template/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
	<div class="col-12">
		<div class="card">
			<div class="card-header d-flex align-items-center">
				<span class="panel-title">{{ _lang('Update Email Template') }}</span>
			</div>
			<div class="card-body">
				<form method="post" class="validate" autocomplete="off" action="{{ action('EmailTemplateController@update', $id) }}" enctype="multipart/form-data">
					{{ csrf_field()}}
					<input name="_method" type="hidden" value="PATCH">				
					
					<div class="col-md-12">
					 	<div class="form-group">
							<label class="control-label">{{ _lang('Name') }}</label>						
							<input type="text" class="form-control" name="name" value="{{ $emailtemplate->name }}" readOnly="true">
					 	</div>
					</div>
					
					<div class="col-md-12">
						<div class="form-group border border-primary p-3">
							<pre>{{ $vars[$emailtemplate->name] }}</pre>
						</div>
					</div>
					
					<div class="col-md-12">
					 	<div class="form-group">
							<label class="control-label">{{ _lang('Subject') }}</label>						
							<input type="text" class="form-control" name="subject" value="{{ $emailtemplate->subject }}" required>
					 	</div>
					</div>

					<div class="col-md-12">
					 	<div class="form-group">
							<label class="control-label">{{ _lang('Body') }}</label>						
							<textarea class="form-control summernote" name="body">{{ $emailtemplate->body }}</textarea>
					 	</div>
					</div>

					
					<div class="form-group">
					  	<div class="col-md-12">
							<button type="submit" class="btn btn-primary">{{ _lang('Update') }}</button>
					  	</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/backend/administration/email_template/list.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
	<div class="col-12">
		<div class="card">
 			<div class="card-header d-flex align-items-center">
				<span class="panel-title">{{ _lang('Email Templates') }}</span>
			</div>
			<div class="card-body">
				<table class="table table-bordered data-table">
					<thead>
					  	<tr>
							<th>{{ _lang('Name') }}</th>
							<th>{{ _lang('Subject') }}</th>
							<th class="text-center">{{ _lang('Action') }}</th>
					  	</tr>
					</thead>
					<tbody> 
						@foreach($emailtemplates as $emailtemplate)
							<tr id="row_{{ $emailtemplate->id }}">
								<td class='name'>{{ ucwords(str_replace('_',' ',$emailtemplate->name)) }}</td>
								<td class='subject'>{{ $emailtemplate->subject }}</td>
								<td class="text-center">
									<a href="{{action('EmailTemplateController@edit', $emailtemplate['id'])}}" class="btn btn-warning btn-xs"><i class="far fa-edit"></i></a>
									<a href="{{action('EmailTemplateController@show', $emailtemplate['id'])}}" class="btn btn-primary btn-xs"><i class="fas fa-eye"></i></a>
								</td>
							</tr>
						@endforeach
					</tbody>
			  	</table>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/backend/administration/email_template/view.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="card">
			<div class="card-header d-flex align-items-center">
				<span class="panel-title">{{ _lang('View Email Template') }}</span>
			</div>
			<div class="card-body">
			  	<table class="table table-bordered">
					<tr><td>{{ $emailtemplate->subject }}</td></tr>
					<tr><td>{!! xss_clean($emailtemplate->body) !!}</td></tr>		
			  	</table>
			</div>
	  	</div>
 	</div>
</div>
@endsection