routes/web.php
		Route::post('/update_account', 'Website\CustomerController@update_account');
		Route::post('/update_password', 'Website\CustomerController@update_password');
		Route::match(['get','post'], '/add_new_address', 'Website\CustomerController@add_new_address');
		Route::match(['get','patch'], '/update_address/{address_id}', 'Website\CustomerController@update_address');
		Route::get('/delete_address/{address_id}', 'Website\CustomerController@delete_address');
		Route::post('comments/store', 'Website\CommentController@store')->name('comments.store');
		Route::post('reviews/store', 'Website\ReviewsController@store')->name('reviews.store');
	});


	//Apply Tax
	Route::get('/apply_tax/{shipping_state?}/{billing_state?}', 'Website\CheckoutController@apply_tax');
	Route::post('/make_order', 'Website\CheckoutController@make_order');
	Route::get('/payment/{order_id}', 'Website\CheckoutController@payment');

	//Get Variation Price
	Route::post('products/get_variation_price/{product_id}','ProductController@get_variation_price');

	//Add to Cart
	Route::post('/add_to_cart/{product_id}', 'Website\CartController@add_to_cart');
	Route::post('/update_cart', 'Website\CartController@update_cart');
	Route::post('/apply_coupon', 'Website\CartController@apply_coupon');
	Route::get('/remove_coupon/{name}', 'Website\CartController@remove_coupon');
	Route::get('/remove_cart_item/{id}', 'Website\CartController@remove_cart_item');
	Route::get('/shipping_method/{name}', 'Website\CartController@shipping_method');

	//Payment Gateways
	Route::get('gateway/paypal_payment_authorize/{paypal_order_id}/{order_id}', 'Website\GatewayController@paypal_payment_authorize');
	Route::post('gateway/stripe_payment_authorize/{order_id}', 'Website\GatewayController@stripe_payment_authorize');
	Route::post('gateway/razorpay_payment_authorize/{order_id}', 'Website\GatewayController@razorpay_payment_authorize');
	Route::get('gateway/paystack_payment_authorize/{order_id}/{reference}', 'Website\GatewayController@paystack_payment_authorize');
	Route::get('gateway/confirm_order/{type}/{order_id}', 'Website\GatewayController@confirm_order'); //This route is for manual payment

	
	Route::group(['prefix'=> 'admin'], function () {
//	    Route::get('/', function(){
//	    	return redirect('admin/login');
//	    });
	    Auth::routes(['verify' => true]);
	});
  
	Route::get('/logout', 'Auth\LoginController@logout');
	Route::get('/{slug?}', 'Website\WebsiteController@index');
	
	Route::group(['middleware' => ['auth','verified'], 'prefix'=> 'admin'], function () {


	    //Contact
        Route::get('/contact_us', 'ContactUsController@index')->name('contact_us');

        //Slide

        Route::get('/slide', 'SlideController@index')->name('slide.index');
        Route::get('/slide/create', 'SlideController@create')->name('slide.create');
        Route::post('/slide/store','SlideController@store')->name('slide.store');
        Route::get('/slide/edit/{id}','SlideController@edit')->name('slide.edit');
        Route::post('/slide/update','SlideController@update')->name('slide.update');
        Route::delete('/slide/destroy/{id}','SlideController@destroy')->name('slide.destroy');

        //Product

        Route::get('products/search','ProductController@search')->name('products.search');
		Route::get('dashboard', 'DashboardController@index')->middleware('groupPermission:admin,user,customer');
		
		//Profile Controller
		Route::get('profile/edit', 'ProfileController@edit')->middleware('groupPermission:admin,user');
		Route::post('profile/update', 'ProfileController@update')->middleware('groupPermission:admin,user');
		Route::get('profile/change_password', 'ProfileController@change_password')->middleware('groupPermission:admin,user');
		Route::post('profile/update_password', 'ProfileController@update_password')->middleware('groupPermission:admin,user');
		

		/** Admin Only Route **/
		Route::group(['middleware' => ['admin']], function () {


			//User Management
			Route::resource('users','UserController');

			//User Roles
			Route::resource('roles','RoleController');
			
			//Permission Controller
		    Route::get('permission/control/{user_id?}', 'PermissionController@index')->name('permission.index');
			Route::post('permission/store', 'PermissionController@store')->name('permission.store');

			
			//Language Controller
			Route::resource('languages','LanguageController');	
			
			//Utility Controller
			Route::match(['get', 'post'],'general_settings/{store?}', 'UtilityController@settings')->name('settings.update_settings');
			Route::match(['get', 'post'],'theme_option/{page?}/{store?}', 'UtilityController@theme_option')->name('theme_option.update');
			Route::post('upload_logo', 'UtilityController@upload_logo')->name('settings.uplaod_logo');
			Route::get('database_backup_list', 'UtilityController@database_backup_list')->name('database_backups.list');
			Route::get('create_database_backup', 'UtilityController@create_database_backup')->name('database_backups.create');
			Route::delete('destroy_database_backup/{id}', 'UtilityController@destroy_database_backup');
			Route::get('download_database_backup/{id}', 'UtilityController@download_database_backup')->name('database_backups.download');
			Route::post('remove_cache', 'UtilityController@remove_cache')->name('settings.remove_cache');

			//Email Template
			Route::resource('email_templates','EmailTemplateController')->only([
				'index', 'show', 'edit', 'update'
			]);

			//Shipping Methods
			Route::get('shipping_methods', 'UtilityController@shipping_methods')->name('settings.shipping_methods');
			
			
		});

        /** Dynamic Permission **/
		Route::group(['middleware' => ['permission']], function () {

			Route::get('dashboard/total_sales_widget', 'DashboardController@total_sales_widget')->name('dashboard.total_sales_widget');
			Route::get('dashboard/current_day_sales_widget', 'DashboardController@current_day_sales_widget')->name('dashboard.current_day_sales_widget');
			Route::get('dashboard/pending_order_widget', 'DashboardController@pending_order_widget')->name('dashboard.pending_order_widget');
			Route::get('dashboard/total_product_widget', 'DashboardController@total_product_widget')->name('dashboard.total_product_widget');
			Route::get('dashboard/weekly_sales_widget', 'DashboardController@weekly_sales_widget')->name('dashboard.weekly_sales_widget');
			Route::get('dashboard/top_view_items_widget', 'DashboardController@top_view_items_widget')->name('dashboard.top_view_items_widget');
			Route::get('dashboard/recent_order_widget', 'DashboardController@recent_order_widget')->name('dashboard.recent_order_widget');
			
			//Media Controller
			Route::get('media/get_table_data/{type?}/{select_type?}','MediaController@get_table_data');
			Route::resource('media','MediaController')->except([
				'edit', 'update'
			]);

			//Order Controller
			Route::get('orders/get_table_data','OrderController@get_table_data');
			Route::resource('orders','OrderController')->except([
			    'create', 'store', 'edit'
			]);

			//Transaction Controller
			Route::get('transactions/get_table_data','TransactionController@get_table_data');
			Route::get('transactions','TransactionController@index')->name('transactions.index');

			//Product Controller
			Route::post('products/generate_variations','ProductController@generate_variations');
			Route::get('products/get_table_data','ProductController@get_table_data');

			Route::resource('products','ProductController');

			//Comments Controller
			Route::get('product_comments/get_table_data','CommentController@get_table_data');
			Route::get('product_comments/destroy/{id}','CommentController@destroy')->name('product_comments.destroy');
			Route::resource('product_comments','CommentController')->only([
			    'index', 'show'
			]);

			//Reviews Controller
			Route::get('product_reviews/get_table_data','ReviewsController@get_table_data');
			Route::post('product_reviews/bulk_action','ReviewsController@bulk_action')->name('product_reviews.bulk_action');
			Route::resource('product_reviews','ReviewsController')->except([
			    'create', 'store',
			]);

			//Category Controller
			Route::resource('category','CategoryController');

			//Brand Controller
			Route::resource('brands','BrandController');

			//Tag Controller
			Route::resource('tags','TagController');

			//Coupon Controller
			Route::resource('coupons','CouponController');

			//Customer Controller
			Route::resource('customers','CustomerController');

			//Currency Controller
			Route::resource('currency','CurrencyController');

			//Tax Vontroller
			Route::get('taxes/get_states/{country_id}','TaxController@get_states');
			Route::resource('taxes','TaxController');

			//Page Controller
			Route::resource('pages','PageController');

			//Navigation Controller
			Route::resource('navigations','NavigationController');
			Route::post('navigations/store_sorting','NavigationController@store_sorting');
			Route::get('navigation_items/{navigation_id}/create','NavigationItemController@create')->name('navigation_items.create');
			Route::post('navigation_items/store/{navigation_id}','NavigationItemController@store')->name('navigation_items.store');
			Route::get('navigation_items/edit/{id}','NavigationItemController@edit')->name('navigation_items.edit');
			Route::patch('navigation_items/update/{id}','NavigationItemController@update')->name('navigation_items.update');
			Route::get('navigation_items/destroy/{id}','NavigationItemController@destroy')->name('navigation_items.destroy');

		});
	
	});

});

//Socila Login
Route::get('/login/{provider}', 'Auth\SocialController@redirect');
Route::get('/login/{provider}/callback','Auth\SocialController@callback');

//Get State By Country
Route::get('get_states/{country_id}','Website\WebsiteController@get_states');

//Search Products
Route::get('shop/search_products','Website\WebsiteController@search_products');

//Ajax Select2 Controller

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use App\User;
use Validator;
use Hash;

class UserController extends Controller
{
	
	/**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        date_default_timezone_set(get_option('timezone','Asia/Dhaka'));
    }
	
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::where('user_type','user')
                     ->orWhere('user_type','admin')
                     ->orderBy('name','asc')
                     ->get();
        return view('backend.user.list',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        if( ! $request->ajax()){
           return view('backend.user.create');
        }else{
           return view('backend.user.modal.create');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {	
        $validator = Validator::make($request->all(), [
            'name' => 'required|max:255',
			'email' => 'required|email|unique:users|max:255',
			'user_type' => 'required',
			'status' => 'required',
			'profile_picture' => 'nullable|image',
			'password' => 'required|min:6',
        ]);

        if ($validator->fails()) {
            if($request->ajax()){ 
                return response()->json(['result'=>'error','message'=>$validator->errors()->all()]);
            }else{
                return redirect()->route('users.create')
                	             ->withErrors($validator)
                	             ->withInput();
            }			
        }
	
	    $profile_picture = "default.png";
        if($request->hasfile('profile_picture'))
	    {
		    $file = $request->file('profile_picture');
		    $profile_picture = time().$file->getClientOriginalName();
		    $file->move(public_path()."/uploads/profile/", $profile_picture);
	    }

        $user = new User();
        $user->name = $request->input('name');
		$user->email = $request->input('email');
		$user->user_type = $request->input('user_type');
		$user->role_id = $request->input('role_id');
		$user->status = $request->input('status');
		$user->profile_picture = $profile_picture;
		$user->email_verified_at = date('Y-m-d H:i:s');
		$user->password = Hash::make($request->password);

        $user->save();
		
		//Prefix Output
		$user->status = status($user->status);
		$user->user_type = ucwords($user->user_type);
		$user->profile_picture = '<img src="' . profile_picture($user->profile_picture) . '" class="thumb-sm rounded-circle mr-2">';

        if(! $request->ajax()){
           return redirect()->route('users.create')->with('success', _lang('Saved Sucessfully'));
        }else{
           return response()->json(['result'=>'success','action'=>'store','message'=>_lang('Saved Sucessfully'),'data'=>$user, 'table' => '#users_table']);
        }
        
   }
	

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request,$id)
    {
        $user = User::find($id);
        if(! $request->ajax()){
            return view('backend.user.view',compact('user','id'));
        }else{
            return view('backend.user.modal.view',compact('user','id'));
        } 
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request,$id)
    {
        $user = User::find($id);
        if(! $request->ajax()){
            return view('backend.user.edit',compact('user','id'));
        }else{
            return view('backend.user.modal.edit',compact('user','id'));
        }  
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
		$validator = Validator::make($request->all(), [
			'name' => 'required|max:255',
			'email' => [
                'required',
				'email',
                Rule::unique('users')->ignore($id),
            ],
			'user_type' => 'required',
			'status' => 'required',
			'profile_picture' => 'nullable|image',
			'password' => 'nullable|min:6',
		]);

		if ($validator->fails()) {
			if($request->ajax()){ 
				return response()->json(['result'=>'error','message'=>$validator->errors()->all()]);
			}else{
				return redirect()->route('users.edit', $id)
							->withErrors($validator)
							->withInput();
			}			
		}
	
        if($request->hasfile('profile_picture'))
	    {
		    $file = $request->file('profile_picture');
		    $profile_picture = time().$file->getClientOriginalName();
		    $file->move(public_path()."/uploads/profile/", $profile_picture);
	    }	
		
        $user = User::find($id);
		$user->name = $request->input('name');
		$user->email = $request->input('email');
		$user->user_type = $request->input('user_type');
		$user->role_id = $request->input('role_id');
		$user->status = $request->input('status');
		if($request->hasfile('profile_picture')){
			$user->profile_picture = $profile_picture;
		}
		if($request->password){
            $user->password = Hash::make($request->password);
        }
	
        $user->save();
		
		//Prefix Output
		$user->status = status($user->status);
		$user->user_type = ucwords($user->user_type);
		$user->profile_picture = '<img src="' . profile_picture($user->profile_picture) . '" class="thumb-sm rounded-circle mr-2">';

		
		if(! $request->ajax()){
           return redirect()->route('users.index')->with('success', _lang('Updated Sucessfully'));
        }else{
		   return response()->json(['result'=>'success','action'=>'update', 'message'=>_lang('Updated Sucessfully'),'data'=>$user, 'table' => '#users_table']);
		}
	    
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();
        return redirect()->route('users.index')->with('success',_lang('Deleted Sucessfully'));
    }
    public function AuthRouteAPI(Request $request){
        return $request->user();
    }
}

resources/views/backend/user/create.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
	<div class="col-lg-12">
		<div class="card">
			<div class="card-header">
				<span class="panel-title">{{ _lang('Create User') }}</span>
			</div>
			<div class="card-body">
			    <form method="post" class="validate" autocomplete="off" action="{{ route('users.store') }}" enctype="multipart/form-data">
					{{ csrf_field() }}
					<div class="row">
						<div class="col-md-6">
							<div class="form-group">
								<label class="control-label">{{ _lang('Name') }}</label>						
								<input type="text" class="form-control" name="name" value="{{ old('name') }}" required>
							</div>
						</div>

						<div class="col-md-6">
							<div class="form-group">
								<label class="control-label">{{ _lang('Email') }}</label>						
								<input type="text" class="form-control" name="email" value="{{ old('email') }}" required>
							</div>
						</div>
						
						
						<div class="col-md-6">
							<div class="form-group">
								<label class="control-label">{{ _lang('Password') }}</label>						
								<input type="password" class="form-control" name="password" value="{{ old('password') }}" required>
							</div>
						</div>

						<div class="col-md-6">
							<div class="form-group">
								<label class="control-label">{{ _lang('User Type') }}</label>						
								<select class="form-control select2 auto-select" data-selected="{{ old('user_type') }}" name="user_type" required>
									<option value="">{{ _lang('Select One') }}</option>
									<option value="admin">{{ _lang('Admin') }}</option>
									<option value="user">{{ _lang('User') }}</option>
								</select>
							</div>
						</div>
						
						<div class="col-md-6">
							<div class="form-group">
								<label class="control-label">{{ _lang('User Role') }}</label>						
								<select class="form-control select2 auto-select" data-selected="{{ old('role_id') }}" name="role_id">
									<option value="">{{ _lang('Select One') }}</option>
									{{ create_option('roles','id','name') }}
								</select>
							</div>
						</div>

						<div class="col-md-6">
							<div class="form-group">
								<label class="control-label">{{ _lang('Status') }}</label>						
								<select class="form-control select2 auto-select" data-selected="{{ old('status') }}" name="status" required>
									<option value="">{{ _lang('Select One') }}</option>
									<option value="1">{{ _lang('Active') }}</option>
									<option value="0">{{ _lang('In Active') }}</option>
								</select>
							</div>
						</div>

						<div class="col-md-6">
							<div class="form-group">
								<label class="control-label">{{ _lang('Profile Picture') }}</label>						
								<input type="file" class="form-control dropify" name="profile_picture" >
							</div>
						</div>

						
						<div class="col-md-12">
							<div class="form-group">
								<button type="reset" class="btn btn-danger">{{ _lang('Reset') }}</button>
								<button type="submit" class="btn btn-primary">{{ _lang('Save') }}</button>
							</div>
						</div>
					</div>			
			    </form>
			</div>
		</div>
    </div>
</div>
@endsection

resources/views/backend/user/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
	<div class="col-lg-12">
		<div class="card">
			<div class="card-header">
				<span class="panel-title">{{ _lang('Update User') }}</span>
			</div>
			<div class="card-body">
				<form method="post" class="validate" autocomplete="off" action="{{ action('UserController@update', $id) }}" enctype="multipart/form-data">
					{{ csrf_field()}}
					<input name="_method" type="hidden" value="PATCH">				
					<div class="row">
						<div class="col-md-6">
							<div class="form-group">
							   <label class="control-label">{{ _lang('Name') }}</label>						
							   <input type="text" class="form-control" name="name" value="{{ $user->name }}" required>
							</div>
						</div>

						<div class="col-md-6">
							<div class="form-group">
							   <label class="control-label">{{ _lang('Email') }}</label>						
							   <input type="text" class="form-control" name="email" value="{{ $user->email }}" required>
							</div>
						</div>
						
						<div class="col-md-6">
							<div class="form-group">
							   <label class="control-label">{{ _lang('Password') }}</label>						
							   <input type="password" class="form-control" name="password" value="">
							</div>
						</div>

						<div class="col-md-6">
							<div class="form-group">
								<label class="control-label">{{ _lang('User Type') }}</label>						
								<select class="form-control select2 auto-select" data-selected="{{ $user->user_type }}" name="user_type" required>
									<option value="">{{ _lang('Select One') }}</option>
									<option value="admin">{{ _lang('Admin') }}</option>
									<option value="user">{{ _lang('User') }}</option>
								</select>
							</div>
						</div>
						
						<div class="col-md-6">
							<div class="form-group">
								<label class="control-label">{{ _lang('User Role') }}</label>						
								<select class="form-control select2 auto-select" data-selected="{{ $user->role_id }}" name="role_id">
									<option value="">{{ _lang('Select One') }}</option>
									{{ create_option('roles','id','name') }}
								</select>
							</div>
						</div>

						<div class="col-md-6">
							<div class="form-group">
								<label class="control-label">{{ _lang('Status') }}</label>						
								<select class="form-control select2 auto-select" data-selected="{{ $user->status }}" name="status" required>
									<option value="">{{ _lang('Select One') }}</option>
									<option value="1">{{ _lang('Active') }}</option>
									<option value="0">{{ _lang('In Active') }}</option>
								</select>
							</div>
						</div>

						<div class="col-md-6">
							<div class="form-group">
							   <label class="control-label">{{ _lang('Profile Picture') }}</label>						
							   <input type="file" class="form-control dropify" name="profile_picture">
							</div>
						</div>

						
						<div class="col-md-12">
							<div class="form-group">
								<button type="submit" class="btn btn-primary">{{ _lang('Update') }}</button>
							</div>
						</div>	
					</div>	
				</form>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/backend/user/list.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
	<div class="col-lg-12">
		<div class="card">
		    <div class="card-header d-flex align-items-center">
				<span class="panel-title">{{ _lang('User List') }}</span>
				<a class="btn btn-primary btn-xs ml-auto ajax-modal" data-title="{{ _lang('Create User') }}" href="{{ route('users.create') }}">{{ _lang('Add New') }}</a>
			</div>
			<div class="card-body">
				<table id="users_table" class="table table-bordered data-table">
					<thead>
					    <tr>
							<th class="text-center">#</th>
						    <th>{{ _lang('Name') }}</th>
							<th>{{ _lang('Email') }}</th>
							<th>{{ _lang('User Type') }}</th>
							<th>{{ _lang('Status') }}</th>
							<th class="text-center">{{ _lang('Action') }}</th>
					    </tr>
					</thead>
					<tbody>
					    @foreach($users as $user)
					    <tr data-id="row_{{ $user->id }}">
							<td class='profile_picture text-center'><img src="{{ profile_picture($user->profile_picture) }}" class="thumb-sm rounded-circle mr-2"></td>
							<td class='name'>{{ $user->name }}</td>
							<td class='email'>{{ $user->email }}</td>
							<td class='user_type'>{{ $user->user_type }}</td>
							<td class='status'>{!! xss_clean(status($user->status)) !!}</td>
							<td class="text-center">
								<div class="dropdown">
								  <button class="btn btn-light dropdown-toggle btn-xs" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								  {{ _lang('Action') }}
								  <i class="fas fa-angle-down"></i>
								  </button>
								  <form action="{{ action('UserController@destroy', $user['id']) }}" method="post">
									{{ csrf_field() }}
									<input name="_method" type="hidden" value="DELETE">
									
									<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
										<a href="{{ action('UserController@edit', $user['id']) }}" data-title="{{ _lang('Update User') }}" class="dropdown-item dropdown-edit ajax-modal"><i class="mdi mdi-pencil"></i> {{ _lang('Edit') }}</a>
										<a href="{{ action('UserController@show', $user['id']) }}" data-title="{{ _lang('View User') }}" class="dropdown-item dropdown-view ajax-modal"><i class="mdi mdi-eye"></i> {{ _lang('View') }}</a>
										<button class="btn-remove dropdown-item" type="submit"><i class="mdi mdi-delete"></i> {{ _lang('Delete') }}</button>
									</div>
								  </form>
								</div>
							</td>
					    </tr>
					    @endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/backend/user/view.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
	<div class="col-lg-12">
		<div class="card">
		    <div class="card-header">
				<span class="panel-title">{{ _lang('View User') }}</span>
			</div>
			
			<div class="card-body">
			    <table class="table table-bordered">
				    <tr><td>{{ _lang('Name') }}</td><td>{{ $user->name }}</td></tr>
					<tr><td>{{ _lang('Email') }}</td><td>{{ $user->email }}</td></tr>
					<tr><td>{{ _lang('User Type') }}</td><td>{{ $user->user_type }}</td></tr>
					<tr><td>{{ _lang('User Role') }}</td><td>{{ $user->role->name }}</td></tr>
					<tr><td>{{ _lang('Status') }}</td><td>{!! xss_clean(status($user->status)) !!}</td></tr>
			    </table>
			</div>
	    </div>
	</div>
</div>
@endsection